// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance.Data;

#nullable disable

namespace Persistance.Migrations
{
    [DbContext(typeof(EStoreDbContext))]
    [Migration("20260422073025_AddAddressClass")]
    partial class AddAddressClass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Address.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Domain.Entities.Cart.Cart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CartStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UniqueCartId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Domain.Entities.Cart.CartItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CartId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Domain.Entities.ProductModule.Brand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaKeywords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("randStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreateDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(2961), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Apple Inc.",
                            IsDeleted = false,
                            MetaDescription = "Apple products",
                            MetaKeywords = "apple,mac,iphone",
                            ModifiedDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(2966), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Apple",
                            Slug = "apple",
                            randStatus = 0
                        },
                        new
                        {
                            Id = 2L,
                            CreateDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(2971), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Samsung Electronics",
                            IsDeleted = false,
                            MetaDescription = "Samsung products",
                            MetaKeywords = "samsung,galaxy",
                            ModifiedDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(2971), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Samsung",
                            Slug = "samsung",
                            randStatus = 0
                        },
                        new
                        {
                            Id = 3L,
                            CreateDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(2974), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Nike Inc.",
                            IsDeleted = false,
                            MetaDescription = "Nike products",
                            MetaKeywords = "nike,shoes,sports",
                            ModifiedDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(2974), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Nike",
                            Slug = "nike",
                            randStatus = 0
                        },
                        new
                        {
                            Id = 4L,
                            CreateDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(2977), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Adidas AG",
                            IsDeleted = false,
                            MetaDescription = "Adidas products",
                            MetaKeywords = "adidas,shoes,sports",
                            ModifiedDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(2977), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Adidas",
                            Slug = "adidas",
                            randStatus = 0
                        },
                        new
                        {
                            Id = 5L,
                            CreateDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(2980), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Sony Corporation",
                            IsDeleted = false,
                            MetaDescription = "Sony products",
                            MetaKeywords = "sony,electronics",
                            ModifiedDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(2980), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Sony",
                            Slug = "sony",
                            randStatus = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProductModule.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CategoryStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaKeywords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryStatus = 0,
                            CreateDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(4799), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Laptop computers",
                            IsDeleted = false,
                            MetaDescription = "Best laptops",
                            MetaKeywords = "laptops,computers",
                            ModifiedDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(4800), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Laptops",
                            Slug = "laptops"
                        },
                        new
                        {
                            Id = 2L,
                            CategoryStatus = 0,
                            CreateDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(4803), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Mobile phones",
                            IsDeleted = false,
                            MetaDescription = "Best phones",
                            MetaKeywords = "phones,mobile",
                            ModifiedDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(4804), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Phones",
                            Slug = "phones"
                        },
                        new
                        {
                            Id = 3L,
                            CategoryStatus = 0,
                            CreateDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(4807), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Sports shoes",
                            IsDeleted = false,
                            MetaDescription = "Best shoes",
                            MetaKeywords = "shoes,sports",
                            ModifiedDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(4808), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Shoes",
                            Slug = "shoes"
                        },
                        new
                        {
                            Id = 4L,
                            CategoryStatus = 0,
                            CreateDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(4811), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Televisions",
                            IsDeleted = false,
                            MetaDescription = "Best TVs",
                            MetaKeywords = "tv,television,sony",
                            ModifiedDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(4812), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "TVs",
                            Slug = "tvs"
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProductModule.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BrandId")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaKeywords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductStatus")
                        .HasColumnType("int");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BrandId = 1L,
                            CategoryId = 1L,
                            CreateDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(6110), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Apple MacBook Pro 14 inch",
                            ImageUrl = "macbook-pro-14.jpg",
                            IsBestSeller = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            MetaDescription = "MacBook Pro 14",
                            MetaKeywords = "apple,macbook,laptop",
                            Model = "MBP14",
                            ModifiedDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(6111), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "MacBook Pro 14",
                            OldPrice = 2099.99m,
                            Price = 1999.99m,
                            ProductStatus = 0,
                            QuantityInStock = 50,
                            SKU = "APL-MBP-14",
                            SalePrice = 1899.99m,
                            Slug = "macbook-pro-14"
                        },
                        new
                        {
                            Id = 2L,
                            BrandId = 1L,
                            CategoryId = 1L,
                            CreateDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(6117), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Apple MacBook Air M2",
                            ImageUrl = "macbook-air-m2.jpg",
                            IsBestSeller = true,
                            IsDeleted = false,
                            IsFeatured = false,
                            MetaDescription = "MacBook Air M2",
                            MetaKeywords = "apple,macbook,laptop",
                            Model = "MBAM2",
                            ModifiedDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(6118), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "MacBook Air M2",
                            OldPrice = 1399.99m,
                            Price = 1299.99m,
                            ProductStatus = 0,
                            QuantityInStock = 75,
                            SKU = "APL-MBA-M2",
                            SalePrice = 1199.99m,
                            Slug = "macbook-air-m2"
                        },
                        new
                        {
                            Id = 3L,
                            BrandId = 2L,
                            CategoryId = 1L,
                            CreateDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(6124), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Samsung Galaxy Book3 Pro",
                            ImageUrl = "galaxy-book3.jpg",
                            IsBestSeller = false,
                            IsDeleted = false,
                            IsFeatured = true,
                            MetaDescription = "Galaxy Book3",
                            MetaKeywords = "samsung,laptop",
                            Model = "GB3PRO",
                            ModifiedDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(6125), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Samsung Galaxy Book3",
                            OldPrice = 1599.99m,
                            Price = 1499.99m,
                            ProductStatus = 0,
                            QuantityInStock = 40,
                            SKU = "SAM-GB3-PRO",
                            SalePrice = 1399.99m,
                            Slug = "samsung-galaxy-book3"
                        },
                        new
                        {
                            Id = 4L,
                            BrandId = 1L,
                            CategoryId = 2L,
                            CreateDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(6135), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Apple iPhone 15 Pro",
                            ImageUrl = "iphone-15-pro.jpg",
                            IsBestSeller = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            MetaDescription = "iPhone 15 Pro",
                            MetaKeywords = "apple,iphone,phone",
                            Model = "IP15PRO",
                            ModifiedDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(6136), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "iPhone 15 Pro",
                            OldPrice = 1099.99m,
                            Price = 999.99m,
                            ProductStatus = 0,
                            QuantityInStock = 100,
                            SKU = "APL-IP15-PRO",
                            SalePrice = 949.99m,
                            Slug = "iphone-15-pro"
                        },
                        new
                        {
                            Id = 5L,
                            BrandId = 1L,
                            CategoryId = 2L,
                            CreateDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(6203), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Apple iPhone 15",
                            ImageUrl = "iphone-15.jpg",
                            IsBestSeller = true,
                            IsDeleted = false,
                            IsFeatured = false,
                            MetaDescription = "iPhone 15",
                            MetaKeywords = "apple,iphone,phone",
                            Model = "IP15",
                            ModifiedDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(6204), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "iPhone 15",
                            OldPrice = 899.99m,
                            Price = 799.99m,
                            ProductStatus = 0,
                            QuantityInStock = 120,
                            SKU = "APL-IP15",
                            SalePrice = 749.99m,
                            Slug = "iphone-15"
                        },
                        new
                        {
                            Id = 6L,
                            BrandId = 2L,
                            CategoryId = 2L,
                            CreateDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(6209), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Samsung Galaxy S24 Ultra",
                            ImageUrl = "galaxy-s24.jpg",
                            IsBestSeller = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            MetaDescription = "Galaxy S24",
                            MetaKeywords = "samsung,galaxy,phone",
                            Model = "GS24ULT",
                            ModifiedDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(6209), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Samsung Galaxy S24",
                            OldPrice = 1299.99m,
                            Price = 1199.99m,
                            ProductStatus = 0,
                            QuantityInStock = 80,
                            SKU = "SAM-GS24-ULT",
                            SalePrice = 1099.99m,
                            Slug = "samsung-galaxy-s24"
                        },
                        new
                        {
                            Id = 7L,
                            BrandId = 3L,
                            CategoryId = 3L,
                            CreateDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(6213), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Nike Air Max 270",
                            ImageUrl = "air-max-270.jpg",
                            IsBestSeller = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            MetaDescription = "Air Max 270",
                            MetaKeywords = "nike,shoes,airmax",
                            Model = "AM270",
                            ModifiedDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(6214), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Nike Air Max 270",
                            OldPrice = 159.99m,
                            Price = 150.00m,
                            ProductStatus = 0,
                            QuantityInStock = 200,
                            SKU = "NK-AM-270",
                            SalePrice = 129.99m,
                            Slug = "nike-air-max-270"
                        },
                        new
                        {
                            Id = 8L,
                            BrandId = 3L,
                            CategoryId = 3L,
                            CreateDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(6218), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Nike Revolution 6",
                            ImageUrl = "revolution-6.jpg",
                            IsBestSeller = false,
                            IsDeleted = false,
                            IsFeatured = false,
                            MetaDescription = "Revolution 6",
                            MetaKeywords = "nike,shoes,running",
                            Model = "REV6",
                            ModifiedDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(6219), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Nike Revolution 6",
                            OldPrice = 89.99m,
                            Price = 80.00m,
                            ProductStatus = 0,
                            QuantityInStock = 150,
                            SKU = "NK-REV-6",
                            SalePrice = 69.99m,
                            Slug = "nike-revolution-6"
                        },
                        new
                        {
                            Id = 9L,
                            BrandId = 4L,
                            CategoryId = 3L,
                            CreateDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(6223), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Adidas Ultraboost 23",
                            ImageUrl = "ultraboost-23.jpg",
                            IsBestSeller = true,
                            IsDeleted = false,
                            IsFeatured = true,
                            MetaDescription = "Ultraboost 23",
                            MetaKeywords = "adidas,shoes,ultraboost",
                            Model = "UB23",
                            ModifiedDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(6224), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Adidas Ultraboost 23",
                            OldPrice = 199.99m,
                            Price = 190.00m,
                            ProductStatus = 0,
                            QuantityInStock = 100,
                            SKU = "AD-UB-23",
                            SalePrice = 169.99m,
                            Slug = "adidas-ultraboost-23"
                        },
                        new
                        {
                            Id = 10L,
                            BrandId = 5L,
                            CategoryId = 4L,
                            CreateDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(6228), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Sony BRAVIA XR 55 inch 4K",
                            ImageUrl = "bravia-xr-55.jpg",
                            IsBestSeller = false,
                            IsDeleted = false,
                            IsFeatured = true,
                            MetaDescription = "BRAVIA XR 55",
                            MetaKeywords = "sony,tv,bravia,4k",
                            Model = "BRV55XR",
                            ModifiedDate = new DateTimeOffset(new DateTime(2026, 4, 22, 7, 30, 24, 123, DateTimeKind.Unspecified).AddTicks(6228), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Sony BRAVIA XR 55",
                            OldPrice = 1399.99m,
                            Price = 1299.99m,
                            ProductStatus = 0,
                            QuantityInStock = 30,
                            SKU = "SNY-BRV-55",
                            SalePrice = 1199.99m,
                            Slug = "sony-bravia-xr-55"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Cart.CartItem", b =>
                {
                    b.HasOne("Domain.Entities.Cart.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ProductModule.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.ProductModule.Product", b =>
                {
                    b.HasOne("Domain.Entities.ProductModule.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ProductModule.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.Cart.Cart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
